[font]
# 用于内置显示器时
# size = 14

# 用于外接显示器时
size = 24

[window]
opacity = 0.92
dynamic_padding = true

[keyboard]
bindings = [
   { key = "Return", mods = "Super|Shift", action = "CreateNewWindow" }
]

