[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd ~/Github/dotfiles/"
desc = "Go dotfiles/"

[[mgr.prepend_keymap]]
on   = [ "g", "C" ]
run  = "cd ~/.config/"
desc = "Go .config/"

[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/Documents/"
desc = "Go Documents/"

[[mgr.prepend_keymap]]
on   = [ "g", "v" ]
run  = "cd ~/Videos/"
desc = "Go Videos/"

[[mgr.prepend_keymap]]
on   = [ "g", "m" ]
run  = "cd ~/Music/"
desc = "Go Music/"

